### ISSUE TITLE
The link to Cyclone in the README doesn't work

### ISSUE THREAD

**Issue by divs1210** [cyclone-scheme/winds#36]
title

**Comment by justinethier** [comment]
Thanks for the report @divs1210! For now I have updated the link to point directly to the homepage on Github.

@arthurmaciel - There is a 403 (Forbidden) error accessing `https://cyclone-scheme.org/`. Looks like there is some problem at the server.

**Comment by arthurmaciel** [comment]
Thanks, @divs1210 and @justinethier. 

@justinethier: do you think for redirection purposes and `https` domain is necessary? I ask because I don't see any harm and `https://cyclone-scheme.org` still works. In fact I am not sure I have ever provided `https://cyclone-scheme.org` at all. I am considering I just made a typo at Winds docs and it (maybe) generated a pseudo-problem. If you think and `https` domain is necessary to redirection purposes please let me know.

**Comment by justinethier** [comment]
@arthurmaciel Ah, I see, everything works fine when using http://cyclone-scheme.org. I think that works well for our purposes since the site is just informational. No need to make things more complicated by requiring `https` at this time. Anyway, thanks for setting this up! :)
